### ISSUE TITLE
yarn.lock and package-lock.json

### ISSUE THREAD

**Issue by wizicer** [Yakuhito/tibet-ui#15]
yarn.lock and package-lock.json should not both exist, choose one package manager to avoid confusion

**Comment by JonathanLangton1** [comment]
Thanks for raising - the `yarn.lock` file was removed in our recent pull [here](https://github.com/Yakuhito/tibet-ui/commit/6437ceed45b29239275c9f049c2ef96b7d8a6c58#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2de) 🙂
